# -*- coding: utf-8 -*-
"""noise_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dmo0Yf70caGcOwq8uGbJ_gCDr4xZRSAM
"""

"""
Noise and decoherence models
"""

import numpy as np

from qutip import destroy, sigmaz


def collapse_operators(T1=None, T2=None):
    """
    Construct Lindblad collapse operators

    Parameters
    ----------
    T1 : float
        Energy relaxation time

    T2 : float
        Dephasing time

    Returns
    -------
    list
        Collapse operators
    """

    c_ops = []

    # Amplitude damping
    if T1 is not None:

        gamma1 = 1 / T1

        c_ops.append(
            np.sqrt(gamma1) * destroy(2)
        )

    # Pure dephasing
    if T2 is not None:

        gamma_phi = 1 / T2

        c_ops.append(
            np.sqrt(gamma_phi) * sigmaz()
        )

    return c_ops