# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_PU68JvE6NJoUAZwSEIgV4cvUXK3No_M
"""

"""
Main execution pipeline
"""

from simulation.pulse_simulator import (
    simulate_pulse
)

from optimization.optimize_pulse import (
    optimize_pulse
)

from visualization.bloch_visualization import (
    plot_bloch_dynamics
)

from qiskit_layer.qiskit_verification import (
    build_reference_x_gate,
    verify_target_state
)


def main():

    print("\n==============================")
    print(" QUANTUM CONTROL SIMULATION ")
    print("==============================\n")

    # -----------------------------------
    # Baseline pulse simulation
    # -----------------------------------

    fidelity, tlist, result = (
        simulate_pulse(1.0)
    )

    print(
        f"Baseline fidelity: "
        f"{fidelity:.6f}"
    )

    # -----------------------------------
    # Pulse optimization
    # -----------------------------------

    best_amp, best_fidelity = (
        optimize_pulse()
    )

    print("\nOptimization Results")
    print("----------------------")

    print(
        f"Optimal amplitude: "
        f"{best_amp:.6f}"
    )

    print(
        f"Optimal fidelity: "
        f"{best_fidelity:.6f}"
    )

    # -----------------------------------
    # Re-simulate optimized pulse
    # -----------------------------------

    fidelity, tlist, result = (
        simulate_pulse(best_amp)
    )

    # -----------------------------------
    # Bloch sphere visualization
    # -----------------------------------

    plot_bloch_dynamics(
        result,
        tlist
    )

    # -----------------------------------
    # Qiskit verification layer
    # -----------------------------------

    qc = build_reference_x_gate()

    print("\nReference X-Gate Circuit")
    print("--------------------------")

    print(qc.draw())

    ideal_state = verify_target_state()

    print("\nIdeal Final Statevector")
    print("--------------------------")

    print(ideal_state)


if __name__ == "__main__":

    main()