# -*- coding: utf-8 -*-
"""optimize_pulse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LCrkhPnoRL5kVcChyyxB0eYxN2C_Avl
"""

"""
Pulse optimization routines
"""

from scipy.optimize import minimize

from simulation.pulse_simulator import (
    simulate_pulse
)


def objective(x):
    """
    Optimization objective

    Parameters
    ----------
    x : ndarray
        Optimization parameters

    Returns
    -------
    float
        Negative fidelity
    """

    amplitude = x[0]

    fidelity, _, _ = simulate_pulse(
        amplitude
    )

    return -fidelity


def optimize_pulse():
    """
    Optimize pulse amplitude

    Returns
    -------
    best_amp : float
        Optimal amplitude

    best_fidelity : float
        Maximum fidelity
    """

    result = minimize(
        objective,
        x0=[1.0],
        bounds=[(0.01, 10.0)],
        method="L-BFGS-B"
    )

    best_amp = result.x[0]

    best_fidelity, _, _ = simulate_pulse(
        best_amp
    )

    return best_amp, best_fidelity