# -*- coding: utf-8 -*-
"""pulse_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rh2ZiyR2bouwZjUHFAMHL75n7Uut-RKV
"""

"""
Open quantum system pulse simulation
"""

import numpy as np

from qutip import (
    basis,
    sigmax,
    sigmaz,
    mesolve
)

from config.system_config import (
    QUBIT_FREQ,
    DRIVE_FREQ,
    T1,
    T2,
    SIGMA,
    DURATION,
    N_STEPS
)

from pulses.pulse_shapes import gaussian_pulse

from noise.noise_model import collapse_operators


def simulate_pulse(amplitude):
    """
    Simulate noisy driven qubit dynamics

    Parameters
    ----------
    amplitude : float
        Pulse amplitude

    Returns
    -------
    fidelity : float
        Final state fidelity

    tlist : ndarray
        Time points

    result : qutip.Result
        Full solver result
    """

    # Initial state density matrix
    rho0 = basis(2, 0).proj()

    # Rotating-frame detuning
    delta = QUBIT_FREQ - DRIVE_FREQ

    # Drift Hamiltonian
    H0 = 0.5 * delta * sigmaz()

    # Time grid
    tlist = np.linspace(
        0,
        DURATION,
        N_STEPS
    )

    # Pulse center
    center = DURATION / 2

    # Time-dependent pulse coefficient
    def pulse_coeff(t, args):

        return gaussian_pulse(
            t=t,
            amp=args["amp"],
            sigma=args["sigma"],
            center=args["center"]
        )

    # Control Hamiltonian
    Hx = 0.5 * sigmax()

    # Full Hamiltonian
    H = [
        H0,
        [Hx, pulse_coeff]
    ]

    # Collapse operators
    c_ops = collapse_operators(
        T1=T1,
        T2=T2
    )

    # Solve Lindblad master equation
    result = mesolve(
        H,
        rho0,
        tlist,
        c_ops=c_ops,
        args={
            "amp": amplitude,
            "sigma": SIGMA,
            "center": center
        }
    )

    # Final density matrix
    rho_final = result.states[-1]

    # Target state |1><1|
    target = basis(2, 1).proj()

    # Fidelity
    fidelity = (
        target * rho_final
    ).tr().real

    return fidelity, tlist, result
