# -*- coding: utf-8 -*-
"""system_config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111ob3oR_VcTytEUrqepoeynQttjAn1AT
"""

"""
System-wide physical parameters
"""

import numpy as np

PI = np.pi

# Qubit frequency
QUBIT_FREQ = 5.0 * 2 * PI

# Drive frequency
DRIVE_FREQ = 5.0 * 2 * PI

# Relaxation and dephasing times
T1 = 20.0
T2 = 30.0

# Pulse parameters
SIGMA = 2.0
DURATION = 20.0

# Simulation resolution
N_STEPS = 1000