# -*- coding: utf-8 -*-
"""qiskit_verification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wcEZqbLamQBSmA4DoM02GLKWwe1f-J5
"""

"""
Qiskit verification layer

This module constructs an ideal X-gate
using Qiskit and verifies the expected
target quantum state.
"""

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector


def build_reference_x_gate():
    """
    Construct ideal X gate circuit.

    Returns
    -------
    QuantumCircuit
        Single-qubit X gate circuit
    """

    qc = QuantumCircuit(1)

    # Apply Pauli-X gate
    qc.x(0)

    return qc


def verify_target_state():
    """
    Simulate ideal X gate evolution.

    Returns
    -------
    Statevector
        Final ideal statevector
    """

    qc = build_reference_x_gate()

    state = Statevector.from_instruction(qc)

    return state


if __name__ == "__main__":

    qc = build_reference_x_gate()

    print("Reference X-Gate Circuit")
    print(qc.draw())

    state = verify_target_state()

    print("\nIdeal Final Statevector")
    print(state)