# -*- coding: utf-8 -*-
"""bloch_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZIT6UL3hGzrBoIoeT67tqeUYRtqktyK
"""

"""
Bloch sphere visualization tools
"""

import matplotlib.pyplot as plt

from qutip import (
    sigmax,
    sigmay,
    sigmaz,
    expect
)


def plot_bloch_dynamics(result, tlist):
    """
    Plot Bloch expectation values in a high-contrast dashboard style,
    consistent with the AutoPulse-Q visualization theme.
    """

    plt.style.use("dark_background")

    states = result.states

    x = expect(sigmax(), states)
    y = expect(sigmay(), states)
    z = expect(sigmaz(), states)

    fig, ax = plt.subplots(figsize=(9, 5.5))

    # Reference lines: |0> ground state (+1) and |1> target state (-1)
    ax.axhline(1.0, color="white", alpha=0.25, linestyle=":")
    ax.axhline(-1.0, color="white", alpha=0.25, linestyle=":")

    ax.plot(tlist, x, color="#888888", linestyle="--", linewidth=1.8, label="⟨X⟩")
    ax.plot(tlist, y, color="#ff00ff", linewidth=2.4, label="⟨Y⟩")
    ax.plot(tlist, z, color="#00ffcc", linewidth=2.8, label="⟨Z⟩")

    ax.fill_between(tlist, z, color="#00ffcc", alpha=0.12)

    ax.set_title(
        "Bloch Sphere Dynamics",
        fontsize=17,
        fontweight="bold"
    )

    ax.set_xlabel("Time")
    ax.set_ylabel("Expectation Values")
    ax.set_ylim(-1.15, 1.15)

    ax.legend(loc="upper right")
    ax.grid(alpha=0.2)

    fig.tight_layout()

    fig.savefig(
        "results/bloch_dynamics.png",
        dpi=150,
        facecolor=fig.get_facecolor()
    )

    plt.show()
