# -*- coding: utf-8 -*-
"""bloch_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZIT6UL3hGzrBoIoeT67tqeUYRtqktyK
"""

"""
Bloch sphere visualization tools
"""

import matplotlib.pyplot as plt

from qutip import (
    sigmax,
    sigmay,
    sigmaz,
    expect
)


def plot_bloch_dynamics(result, tlist):
    """
    Plot Bloch expectation values
    """

    states = result.states

    x = expect(sigmax(), states)
    y = expect(sigmay(), states)
    z = expect(sigmaz(), states)

    plt.figure(figsize=(8, 5))

    plt.plot(tlist, x, label="⟨X⟩")
    plt.plot(tlist, y, label="⟨Y⟩")
    plt.plot(tlist, z, label="⟨Z⟩")

    plt.xlabel("Time")

    plt.ylabel(
        "Expectation Values"
    )

    plt.title(
        "Bloch Sphere Dynamics"
    )

    plt.grid()

    plt.legend()

    plt.savefig(
        "results/bloch_dynamics.png"
    )

    plt.show()