# -*- coding: utf-8 -*-
"""pulse_shapes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQ6lOBQROmJKPJjXIzE1hN-cXjAkfOu5
"""

"""
Pulse envelope definitions
"""

import numpy as np


def gaussian_pulse(t, amp, sigma, center):
    """
    Gaussian pulse envelope

    Parameters
    ----------
    t : float
        Time value

    amp : float
        Pulse amplitude

    sigma : float
        Gaussian width

    center : float
        Pulse center location

    Returns
    -------
    float
        Pulse amplitude at time t
    """

    return amp * np.exp(
        -(t - center)**2 / (2 * sigma**2)
    )